### ISSUE TITLE
[PE-D][Tester C] Add command DATE 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-3/tp#157]
![Screenshot 2023-03-31 at 2.11.11 PM.png](https://raw.githubusercontent.com/WeideTeo/ped/main/files/69c76245-33f2-4701-82af-b4fd7f30f3cc.png)
Should implement comparing today date to input date. As user might write wrong date and miss his application, as past dates can still be inputted. (This will also cause the upcoming to not reflect an important internship role as the user input it wrongly)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: WeideTeo/ped#2

**Comment by seadragon2000341** [comment]
Not within scope - there are cases where user may log in previous dates
