### ISSUE TITLE
[PE-D][Tester E] Entering multiple values for a single field does not generate an error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-3/tp#161]
![catcherbug1.png](https://raw.githubusercontent.com/jeremykhoo-NUS/ped/main/files/fc42b2db-0944-47c5-a2ee-a29791926e64.png)

# Details: 
When editing an internship entry, I noticed that it is possible to enter multiple values for a single field without generating an error message. For example, when I entered "edit 1 n/banana n/apple n/coconut" to update the name of an internship, program only saved coconut as the name

### Expected behavior: 
I expected to see an error message when I attempted to enter multiple values for a single field, since this behavior is not allowed in the application. Or a prompt to let me choose the field I actually want

### Actual behavior: 
The application allows multiple values to be entered for a single field without generating an error message. This could lead to confusion and inaccurate data, as the user may not realize that the multiple values have been dropped 

### Severity/Type:
I would classify this issue as a medium severity, as it does not prevent the application from functioning, but it could lead to inaccurate data if not addressed. I would label it as a "FeatureFlaw" issue, as it pertains to the way data is entered and saved in the application.

### Problematic scenario: 
As this works for the /r parameter.
1. Say my internship has more than one role and I didn't know I can only add one role so I do 
2. i do "edit 1 r/swe r/toilet cleaner"
3. only my role as "toilet cleaner " will be saved
4. I now think that my internship in company '1' is only as toilet cleaner

Improvement suggestion: I suggest that the application be updated to generate an error message when multiple values are entered for a single field, in order to prevent confusion and ensure accurate data entry.

(the 8 seed text box in the screen cap is my own GUI bug)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jeremykhoo-NUS/ped#1

**Comment by eugenetangkj** [comment]
Similar issue as #170

**Comment by eugenetangkj** [comment]
Fix by #201 and #208
