### ISSUE TITLE
[PE-D][Tester E] Multiple tags confusion

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-3/tp#170]
![catcherbug4.png](https://raw.githubusercontent.com/jeremykhoo-NUS/ped/main/files/10d1b3dc-d7f3-4efb-9cfc-da52512e5216.png)

# Details: 
When attempting to update the role and tags of an internship entry, I noticed that the application saved the tags in a confusing way. For example, when I entered "edit 1 r/swe t/floor sweeper/tester t/r/boss/tag r/plunger" the role r/swe was not saved instead the role of plunger was saved. also the Tags created included the r/ parameter (because of missing spaces but it creates confusion)

## Expected behavior: 
I expected an error as I am not allowed multiple roles. I expected not to be able to set a parameter 'r/' as a string in for tag because it doesn't make sense

## Actual behavior: 
Application dropped the 1st role. and created the tag r/boss/tag

## Type: 
I would classify this issue as a low to medium severity, as it does not prevent the application from functioning, but it could lead to inaccurate data if not addressed. I would label it as a "Feature flaw" issue, as it pertains how this feature is implemented

(floating seed 8 box is my own GUI bug)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jeremykhoo-NUS/ped#2

**Comment by eugenetangkj** [comment]
Should we put this in the appendix for developer guide? Say we can implement a warning if it detects multiple fields of the same type when it is only required once. @AY2223S2-CS2103T-T14-3/developers

**Comment by eugenetangkj** [comment]
Fix by #201 and #208
