### ISSUE TITLE
[PE-D][Tester B] Bug 8 - User Guide Typo: Delete-Field Function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T14-3/tp#174]
delete-field n/Google n/Meta deletes all internship entries that have a status of either Applied or New. However, on testing, keying in above commend does result in given result.

![image.png](https://raw.githubusercontent.com/Karen-Lam/ped/main/files/a487580d-2f15-4d6e-96f4-89d8fded96ac.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Karen-Lam/ped#7

**Comment by eugenetangkj** [comment]
Fix by #195
