### ISSUE TITLE
[PE-D][Tester E] Tag can be blank

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-3/tp#180]
![catcherbug6.png](https://raw.githubusercontent.com/jeremykhoo-NUS/ped/main/files/b4e20fcc-05cb-474e-9adc-803af9eb4826.png)

tags can be blank in the edit command

edit 1 t/ 
is valid

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jeremykhoo-NUS/ped#4

**Comment by eugenetangkj** [comment]
Fix by #187
