### ISSUE TITLE
[PE-D][Tester D] UG - Appendix B: Customising the Data File

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T14-3/tp#182]
Minor detail. Under point 4, constraints doesn't link to anywhere.

![image.png](https://raw.githubusercontent.com/gremmyz/ped/main/files/b0f7b509-e6d6-43cb-8906-dd9f2f343014.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: gremmyz/ped#12

**Comment by eugenetangkj** [comment]
Fix by #187
