### ISSUE TITLE
Add a skeletal PPP

### ISSUE THREAD

**Issue by seadragon2000341** [AY2223S2-CS2103T-T14-3/tp#9]
File name (i.e., in the repo): docs/team/github_username_in_lower_case.md e.g., docs/team/goodcoder123.md
Follow the [example in the AddressBook-Level3](https://se-education.org/addressbook-level3/team/johndoe.html)

**Comment by eugenetangkj** [comment]
Fix by #15, #20, #25, #33 and #35
